#coding: utf-8

PKGS = [{
    "name": "libsc.jcmeasure.test_nop",
    "version": "1.0",
    "aid": "11223344550001",
    "applets": [{
        "name": "TestNop",
        "aid": "1122334455000101"
    }]
}]

from jcbuilder import gen_caps, convert_jca
from pathlib import Path

dist_path = ARGUMENTS.get("DIST_PATH", "../../tests")

# generate cap and jca file by java file
caps = gen_caps(PKGS)
jca = str(Path(str(caps[0])).with_suffix(".jca"))
Depends(jca, caps)

def insert_op(target, source, env):
    jca_lines = open(str(source[0])).readlines()
    with open(str(target[0]), "w") as f:
        f.writelines(jca_lines[:127])
        # insert 10 nop after if_scmpge L5;
        f.writelines(["\t\t\t\t\tnop;\n"] * 10)
        f.writelines(jca_lines[127:])
    
new_jca = Command("test_nop.jca", jca, insert_op)

out = convert_jca("test_nop.cap", new_jca)
inst = Install(dist_path, out + Glob("*.json"))
Default(inst)
